<?php

/**
 * This file is part of my Product Page project.
 *
 * @category  DAO
 * @package   App\Core\Database\DAO
 * @author    Victor Aurélio Rodrigues Ribeiro <victoraurelio_198@hotmail.com>
 * @copyright (c) 2023 Victor Aurelio
 * @link      https://github.com/VictorAurelio/product-page
 */

namespace App\Core\Database\DAO;

use App\Core\Database\DatabaseService\DatabaseService;
use App\Core\Database\QueryBuilder\QueryBuilder;
use Throwable;

/**
 * Summary of DAO
 */
class DAO
{
    /**
     * instance of QueryBuilder class
     *
     * @var QueryBuilder
     */
    protected QueryBuilder $queryBuilder;
    /**
     * instance of DatabaseService class
     *
     * @var DatabaseService
     */
    protected DatabaseService $dataMapper;
    /**
     * string representing the table schema ID
     *
     * @var string
     */
    protected string $tableSchemaID;
    /**
     * string representing the table schema
     *
     * @var string
     */
    protected string $tableSchema;
    /**
     * array variable that holds the options of the DAO instance.
     *
     * @var array
     */
    protected array $options;

    /**
     * constructor method of the DAO class that initializes the DatabaseService,
     * QueryBuilder, table schema, table schema ID, and options of the instance.
     * 
     * @param DatabaseService $dataMapper
     * @param QueryBuilder    $queryBuilder 
     * @param string          $tableSchema
     * @param string          $tableSchemaID
     * @param array|null      $options
     */
    public function __construct(
        DatabaseService $dataMapper,
        QueryBuilder $queryBuilder,
        string $tableSchema,
        string $tableSchemaID,
        ?array $options = []
    ) {
        $this->tableSchemaID = $tableSchemaID;
        $this->queryBuilder = $queryBuilder;
        $this->tableSchema = $tableSchema;
        $this->dataMapper = $dataMapper;
        $this->options = $options;
    }
    /**
     * method that returns the string representation of the table schema
     * of the DAO instance.
     * 
     * @inheritdoc
     *
     * @return string
     */
    public function getSchema(): string
    {
        return (string)$this->tableSchema;
    }
    /**
     * Get the QueryBuilder instance.
     *
     * @return QueryBuilder
     */
    public function getQueryBuilder(): QueryBuilder
    {
        return $this->queryBuilder;
    }
    /**
     * Get the DataMapper instance.
     *
     * @return DatabaseService
     */
    public function getDataMapper(): DatabaseService
    {
        return $this->dataMapper;
    }
    /**
     * Summary of GetSchemaId
     *
     * @inheritdoc
     *
     * @return string
     */
    public function getSchemaID(): string
    {
        return (string)$this->tableSchemaID;
    }
    /**
     * Returns the last ID generated by the database during an insert operation.
     * 
     * @inheritdoc
     *
     * @return integer
     */
    public function lastID(): int
    {
        return $this->dataMapper->getLastId();
    }
    /**
     * Finds and returns an object with exact search fields specified by the
     * parameter array $fields. Uses the query builder to build a search query
     * based on the provided selectors, and executes the query using the
     * data mapper. If there is a match, returns an object; otherwise, returns null.
     *
     * @param array $fields
     * 
     * @return object|null
     */
    public function findByExact(array $fields): ?Object
    {
        $sqlQuery = $this->queryBuilder->buildQuery(
            [
                'type' => 'search',
                'selectors' => $fields,
                'table' => $this->getSchema()
            ]
        )->exactSearchQuery();

        $this->dataMapper->persist(
            $sqlQuery,
            $this->dataMapper->buildQueryParameters([], $fields),
            false
        );
        return $this->dataMapper->result();
    }
    /**
     * This function performs a search query with the specified selectors and
     * conditions on the database table using the QueryBuilder class. If the exact
     * flag is set to true, the query will be executed as an exact search query.
     * It returns an array of results if any records are found, otherwise,
     * it returns an empty array.
     *
     * @param array $selectors
     * @param array $conditions
     * @param bool  $exact
     * 
     * @inheritdoc
     * 
     * @return array
     * 
     * @throws DataLayerException
     */
    public function search(
        array $selectors = [],
        array $conditions = [],
        bool $exact = false
    ): array {
        $args = [
            'table' => $this->getSchema(),
            'type' => 'search',
            'selectors' => $selectors,
            'conditions' => $conditions,
            'isSearch' => !$exact
        ];
        $query = $exact ?
            $this->queryBuilder->buildQuery($args)->searchQueryExact() :
            $this->queryBuilder->buildQuery($args)->searchQuery();

        $this->dataMapper->persist(
            $query,
            $this->dataMapper->buildQueryParameters($conditions),
            true
        );
        return ($this->dataMapper->numRows() >= 1)
             ? $this->dataMapper->results() 
             : array();
    }
    /**
     * This function takes a string as input and checks if it matches with any
     * of the allowed query types. If it does, it returns the corresponding query.     * 
     * Note: The function does not have any side-effects and only returns a value
     * based on the input.
     * 
     * @param string $type
     * 
     * @return mixed
     */
    public function getQueryType(string $type)
    {
        $queryTypes = [
            'createQuery',
            'readQuery',
            'updateQuery',
            'deleteQuery',
            'joinQuery',
            'searchQuery',
            'rawQuery'
        ];
        
        if (empty($type)) {
            return null;
        }
        
        if (in_array($type, $queryTypes, true)) {
            return $this->$type;
        }
        
        return null;
    }
}
